app/blueprints/blog/models.py
from app import db
from datetime import datetime
from app.blueprints.main.models import User

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250), nullable=False)
    body = db.Column(db.String(2500), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref='post')

app/blueprints/main/models.py
from app import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50), unique=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    password= db.Column(db.String(200))

    def hash_my_password(self, password):
        self.password = generate_password_hash(password)

    def check_my_password(self, password):
        return check_password_hash(self.password, password)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

# def hash_passwords():
#     users = User.query.filter(User.id < 4).all()
#     for user in users:
#         user.hash_my_password(user.password)
#         db.session.add(user)
    
#     db.session.commit()

# from app.blueprints.main.models import hash_passwords

app/__init__.py
from flask import Flask, flash, redirect, url_for
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)

    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # from app import routes, models
    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)
    from app.blueprints.blog import bp as blog_bp
    app.register_blueprint(blog_bp)
    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    # create files for each concern (init, routes, etc)

    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'You cannot see this!'
    login_manager.login_message_category = 'danger'

    return app

app/blueprints/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__, url_prefix='/blog')

from . import routes, models

app/blueprints/blog/routes.py
from app import db
from flask import render_template, request, redirect, url_for, flash
from app.blueprints.blog.models import Post, User
from flask_login import current_user, login_required
from . import bp as app



@app.route('/posts')
@login_required
def posts():
    all_posts = Post.query.all()
    return render_template('posts.html.j2', posts= all_posts)

# create a dynamic route to get a single post based on it's id
@app.route('/post/<id>')
@login_required
def post_by_id(id):
    post = Post.query.get(int(id))
    return render_template('post_single.html.j2', post=post)

@app.route('/create-post', methods=["POST"])
@login_required
def create_post():
    title = request.form['inputTitle']
    body = request.form['inputBody']
    new_post = Post(title=title, body=body, user_id=current_user.id)
    db.session.add(new_post)
    db.session.commit()
    flash("Post created successfully.", 'success')
    return redirect(url_for('blog.posts')) # similar redirect without import, using the function name
    return redirect('/blog/posts') # redirect imported from flask

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from . import routes, models

app/blueprints/main/routes.py
from . import bp as app
from flask import render_template
from flask_login import current_user


@app.route('/') 
def home():
    return render_template('home.html', user= current_user)

@app.route('/about')
def about():
    return render_template('about.html')

app/templates/about.html
{% extends './layout.html' %}

{% block title %}About{% endblock title%}


{% block content %}
    <h1>About</h1>
{% endblock content%}

app/templates/car.html.j2
<h1>{{ name }}</h1>
<h2>Year: {{ year }}</h2>
<h2>Sale Price: {{selling_price }}</h2>

app/templates/cars.html.j2
<h1>Cars:</h1>
{% for id, car in car_data.items() %}

<div>
    <h2>{{ car['name'] }}</h2>  
    <h3>Car Id: {{ id }}</h3>

    <p>
    Year: {{ car['year'] }} <br> <br>
    Sale Price: ${{ car['selling_price'] }}
    </p>
<hr>
</div>
{% endfor %}

app/templates/home.html
{% extends './layout.html' %}

{% block title %}Home{% endblock title%}

{% block content %}

    <h1>Home</h1>
    {% if user.is_authenticated %}
<p>Welcome to our app {{ user.username }}</p>
{% else %}
<p>Please <a href="{{ url_for('auth.login') }}">Login</a></p>
{% endif%}

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title%} | Fakebook</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">Fakebook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('blog.posts') }}">Posts</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                More Info
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ url_for('main.about') }}">About</a></li>
                                <!-- <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if current_user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                    </ul>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li> <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.reset_password') }}">Reset Password</a>
                    </li>
                    {% endif%}
                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class=flashes>
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock content %}
    </main>
    <footer class="container">this is the footer</footer>
</body>

</html>

app/templates/login.html
{% extends './layout.html' %}

{% block title %}Login{% endblock title%}


{% block content %}
<h1>Login</h1>

<form action="{{ url_for('auth.login') }}" method="POST">
    <input type="hidden" value="{{ request.args.get('next', '') }}" name = 'next'>

    <div class="mb-3">
        <label for="email" class="form-label">Email address:</label>
        <input type="email" class="form-control" id="email" name="email">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else</div>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password:</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content%}

app/templates/post_single.html.j2
{% extends './layout.html' %}

{% block title %}Post{% endblock title%}

{% block content %}
    <h1>Post</h1>



div class="card">
    <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
      <p><small>{{ post.date_created }}</small></p>
        <p>{{ post.body }}
        </p>
    </div>
    <div class="card-footer">
        This post brought to you by: {{ post.user.username }}
    </div>

</div>

{% endblock content %}

app/templates/posts.html.j2
{% extends './layout.html' %}

{% block title %}Home{% endblock title%}

{% block content %}
<h1>Posts</h1>


<form action="{{ url_for('blog.create_post') }}" method="POST">
    <div class="mb-3">
        <label for="inputTitle" class="form-label">Title:</label>
        <input type="text" class="form-control" id="inputTitle" name="inputTitle">
    </div>
    <div class="mb-3">
        <label for="inputBody" class="form-label">Body:</label>
        <input type="text" class="form-control" id="inputBody" name="inputBody">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{# {{ posts | length }} getting the length of things in ninja #}

{% for post in posts %}
<div class="card">
    <div class="card-body">
    <h5 class="card-title"><a href="{{ url_for('blog.post_by_id', id= post.id) }}">{{post.title}}</h5></a>
      <p><small>{{ post.date_created }}</small></p>
        <p>{{ post.body }}
        </p>
    </div>
    <div class="card-footer">
        This post brought to you by: {{ post.user.username }}
    </div>

</div>


{% endfor%}

{% endblock content %}

app/templates/profile.html.j2
<h1>User: {{ name }}</h1>
<h2>User Info:</h2>
<ul>
    <li>User Id: {{ user_id }}</li>
    <li>Email: {{email }}</li>
    <li>Favoirite Color: {{ favorite_color }}</li>
    <li>Is Active: {{ is_active }}</li>
</ul>
{% if is_active %}
    <h2>Reviews:</h2>
    {% for review in reviews %}
    <div>
        {{ review }}
    </div>
    {% endfor %}
{% else %}
<h2>No Reviews for inactive users</h2>
{% endif %}

app/templates/register.html
{% extends './layout.html' %}

{% block title %}Register{% endblock title%}


{% block content %}
<h1>Register</h1>

<form action="{{ url_for('auth.register') }}" method="POST">
    <div class="mb-3">
        <label for="email" class="form-label">Email address:</label>
        <input type="email" class="form-control" id="email" name="email">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else</div>
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">Username:</label>
        <input type="text" class="form-control" id="username" name="username">
    </div>
    <div class="mb-3">
        <label for="firstName" class="form-label">First Name:</label>
        <input type="text" class="form-control" id="firstName" name="firstName">
    </div>
    <div class="mb-3">
        <label for="lastName" class="form-label">Last Name:</label>
        <input type="text" class="form-control" id="lastName" name="lastName">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password:</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <div class="mb-3">
        <label for="confirmPassword" class="form-label">Confirm Password:</label>
        <input type="password" class="form-control" id="confirmPassword" name="confirmPassword">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content%}

app/templates/reset-password.html
{% extends './layout.html' %}

{% block title %}Login{% endblock title%}


{% block content %}
<h1>Reset Password</h1>

<form action="{{ url_for('auth.reset_password') }}" method="POST">
    <input type="hidden" value="{{ request.args.get('next', '') }}" name = 'next'>

    <div class="mb-3">
        <label for="oldPassword" class="form-label">Old Password:</label>
        <input type="password" class="form-control" id="oldPassword" name="oldPassword">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else</div>
    </div>
    <div class="mb-3">
        <label for="newPassword" class="form-label">New Password:</label>
        <input type="password" class="form-control" id="newPassword" name="newPassword">
    </div>
    <div class="mb-3">
        <label for="confirmNewPassword" class="form-label">Confirm New Password:</label>
        <input type="password" class="form-control" id="confirmNewPassword" name="confirmNewPassword">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content%}